# handlers/constants.py

(
    MENU,
    AWAITING_PACKAGES,
    AWAITING_ROOTFS_SIZE,
    AWAITING_LEECH_DEST,
    SELECT_VERSION_MAJOR,
    SELECT_VERSION_MINOR,
    SELECT_TARGET,
    SELECT_SUBTARGET,
    SELECT_PROFILE,
    SELECT_UPLOAD_PATTERN
) = range(10)
